name: build guestfs-tools container image
on:
  push:
    branches:
      - main
    paths:
      - containers/guestfs-tools/Containerfile
      - .github/workflows/container-guestfs-tools.yml
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

env:
  IMAGE_NAME: guestfs-tools
  IMAGE: ghcr.io/${{ github.repository_owner }}/guestfs-tools
  GET_VERSION_CMD: rpm --query --queryformat "%{VERSION}" guestfs-tools

jobs:
  build:
    name: build container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: run buildah
        run: >-
          buildah bud --format oci --tls-verify=true
          -t ${IMAGE_NAME}:_build
          containers/${IMAGE_NAME}

      - name: get binary version
        id: get_version
        run: |-
          bin_version="$(podman run --rm ${IMAGE_NAME}:_build ${GET_VERSION_CMD})"
          printf 'bin_version=%s\n' "$bin_version" >> "$GITHUB_OUTPUT"

      - name: tag the container image
        id: tag_image
        run: |-
          img_tags="${IMAGE}:latest"
          img_tags="$img_tags ${IMAGE}:${{ steps.get_version.outputs.bin_version }}"
          img_tags="$img_tags ${IMAGE}:$(date -I)"
          podman tag "${IMAGE_NAME}:_build" $img_tags
          printf 'img_tags=%s' "$img_tags" >> "$GITHUB_OUTPUT"

      - name: push to registry
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          tags: ${{ steps.tag_image.outputs.img_tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
